// export const initialFileColumnsData = [
//   {
//     originalColumnName: "documentType",
//     dataTypes: ["string"],
//     numberColumn: "1",
//     possibleMappings: ["fullName"],
//     sampleValues: ["NIF", "NIF", "NIF", "NIF", "NIF"],
//   },
//   {
//     originalColumnName: "monthly_payment",
//     dataTypes: ["double", "string"],
//     numberColumn: "17",
//     possibleMappings: ["brand"],
//     sampleValues: ["91.58", "91.85", "125.6", "53.27", "132.79"],
//   },
//   ...{
//     originalColumnName: "fechaContratacion",
//     dataTypes: ["date", "string"],
//     numberColumn: "12",
//     possibleMappings: ["birthday"],
//     sampleValues: [
//       "01-03-2018",
//       "01-03-2018",
//       "01-03-2018",
//       "01-03-2018",
//       "01-03-2018",
//     ],
//   },
//   {
//     originalColumnName: "phone",
//     dataTypes: ["integer", "string"],
//     numberColumn: "8",
//     possibleMappings: ["phoneNumber", "brand"],
//     sampleValues: [
//       "670748586",
//       "636742903",
//       "675747176",
//       "687787190",
//       "649430638",
//     ],
//   },
//   {
//     originalColumnName: "fechaNacimiento",
//     dataTypes: ["date", "string"],
//     numberColumn: "11",
//     possibleMappings: ["birthday"],
//     sampleValues: [
//       "12-12-1992",
//       "04-04-1974",
//       "10-10-1990",
//       "04-04-1984",
//       "05-05-1985",
//     ],
//   },
//   {
//     originalColumnName: "documentNumber",
//     dataTypes: ["string"],
//     numberColumn: "2",
//     possibleMappings: ["documentNumber"],
//     sampleValues: [
//       "00647449E",
//       "00697861H",
//       "00640208A",
//       "00377193Q",
//       "00377402H",
//     ],
//   },
//   {
//     originalColumnName: "n_monthly_payments",
//     dataTypes: ["double", "string"],
//     numberColumn: "16",
//     possibleMappings: ["name"],
//     sampleValues: ["12.0", "12.0", "10.0", "30.0", "10.0"],
//   },
//   {
//     originalColumnName: "fullName",
//     dataTypes: ["string"],
//     numberColumn: "0",
//     possibleMappings: ["fullName"],
//     sampleValues: [
//       "amparo lajas dominguez",
//       "adolfo gayo",
//       "pedro victorio salcedo lopez",
//       "cayetano martin nombela",
//       "claudio carlos lopez diego",
//     ],
//   },
//   {
//     originalColumnName: "fullAddress",
//     dataTypes: ["string"],
//     numberColumn: "3",
//     possibleMappings: [],
//     sampleValues: [
//       "AV CONSTITUCION 42 ,10868 ,HERN��N-P��REZ ,C��CERES",
//       "AV VALDELAPARRA 120 PL:BAJO PT:E ,28100 ,ALCOBENDAS ,MADRID",
//       "AV SALAMANCA 26 BL:10 PL:6 PT:12 ,03130 ,SANTA POLA ,ALICANTE/ALACANT",
//       "CL GONZALO CORDOBA 61 PL:3 ,28830 ,SAN FERNANDO DE HENARES ,MADRID",
//       "CL SIMONE DE BEAUVOIR 1 BL:5 PL:3 PT:B ,28523 ,RIVAS-VACIAMADRID ,MADRID",
//     ],
//   },
//   {
//     originalColumnName: "credit_amount",
//     dataTypes: ["double", "string"],
//     numberColumn: "14",
//     possibleMappings: [],
//     sampleValues: ["1099.0", "1102.15", "1256.0", "1597.99", "1327.9"],
//   },
//   {
//     originalColumnName: "address",
//     dataTypes: ["string"],
//     numberColumn: "7",
//     possibleMappings: [],
//     sampleValues: [
//       "AV CONSTITUCION 42",
//       "AV VALDELAPARRA 120 BAJO E",
//       "AV SALAMANCA 26 Bloque 10 6�� Pta 12",
//       "CL GONZALO CORDOBA 61 3��",
//       "CL SIMONE DE BEAUVOIR 1 Bloque 5 3��B",
//     ],
//   },
//   {
//     originalColumnName: "fechaFinalizacion",
//     dataTypes: ["date", "string"],
//     numberColumn: "13",
//     possibleMappings: ["birthday"],
//     sampleValues: [
//       "15-12-2020",
//       "15-12-2020",
//       "15-12-2020",
//       "15-12-2020",
//       "15-12-2020",
//     ],
//   },
//   {
//     originalColumnName: "province",
//     dataTypes: ["string"],
//     numberColumn: "4",
//     possibleMappings: ["fullName", "dni", "type"],
//     sampleValues: ["C��CERES", "MADRID", "ALICANTE", "MADRID", "MADRID"],
//   },
//   {
//     originalColumnName: "phone2",
//     dataTypes: ["integer", "string"],
//     numberColumn: "9",
//     possibleMappings: ["type"],
//     sampleValues: ["34653399395", "34916741587", "34649430622", "34649430622"],
//   },
//   {
//     originalColumnName: "tin",
//     dataTypes: ["double", "string"],
//     numberColumn: "15",
//     possibleMappings: ["amount"],
//     sampleValues: ["0.0", "0.0", "0.0", "0.0", "0.0"],
//   },
//   {
//     originalColumnName: "email",
//     dataTypes: ["string"],
//     numberColumn: "10",
//     possibleMappings: ["email"],
//     sampleValues: [
//       "pilar.mafer@yahoo.es",
//       "ami.madrid@hotmail.es",
//       "vicentegperales@hotmail.com",
//       "ami.madrid@hotmail.es",
//       "vicentegperales@hotmail.com",
//     ],
//   },
//   {
//     originalColumnName: "town",
//     dataTypes: ["string"],
//     numberColumn: "5",
//     possibleMappings: ["fullName", "stair"],
//     sampleValues: [
//       "HERN��N-P��REZ",
//       "ALCOBENDAS",
//       "SANTA POLA",
//       "SAN FERNANDO DE HENARES",
//       "RIVAS-VACIAMADRID",
//     ],
//   },
//   {
//     originalColumnName: "zipCode",
//     dataTypes: ["integer", "string"],
//     numberColumn: "6",
//     possibleMappings: ["zipCode"],
//     sampleValues: ["10868", "28100", "03130", "28830", "28523"],
//   },
// ];

// export const initialVariableListData = [
//   {
//     variableName: "dni",
//     dataType: "string",
//     localizedVariableName: null,
//     deprecated: false,
//     necessity: "MINIMUM",
//   },
//   {
//     variableName: "birthday",
//     dataType: "date",
//     localizedVariableName: null,
//     deprecated: false,
//     necessity: "MINIMUM",
//   },
//   {
//     variableName: "target",
//     dataType: "number",
//     localizedVariableName: null,
//     deprecated: false,
//     necessity: "STANDARD_MINIMUM",
//   },
//   {
//     variableName: "email",
//     dataType: "string",
//     localizedVariableName: null,
//     deprecated: false,
//     necessity: "STANDARD_MINIMUM",
//   },
//   {
//     variableName: "phone",
//     dataType: "string",
//     localizedVariableName: null,
//     deprecated: false,
//     necessity: "STANDARD_MINIMUM",
//   },
//   {
//     variableName: "amount",
//     dataType: "number",
//     localizedVariableName: null,
//     deprecated: false,
//     necessity: "STANDARD_MINIMUM",
//   },
//   {
//     variableName: "share",
//     dataType: "number",
//     localizedVariableName: null,
//     deprecated: false,
//     necessity: "STANDARD_MINIMUM",
//   },
//   {
//     variableName: "timeframe",
//     dataType: "number",
//     localizedVariableName: null,
//     deprecated: false,
//     necessity: "STANDARD_MINIMUM",
//   },
//   {
//     variableName: "margin",
//     dataType: "number",
//     localizedVariableName: null,
//     deprecated: false,
//     necessity: "PERFECT",
//   },
//   {
//     variableName: "operationDate",
//     dataType: "date",
//     localizedVariableName: null,
//     deprecated: false,
//     necessity: "PERFECT",
//   },
//   {
//     variableName: "acceptance",
//     dataType: "string",
//     localizedVariableName: null,
//     deprecated: false,
//     necessity: "PERFECT",
//   },
// ];

// export const initialGroupVariablesData = [
//   {
//     variableName: "name",
//     localizedVariableName: null,
//     variables: [
//       {
//         variableName: "fullname",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "name",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "surname1",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "surname2",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "lastname",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//     ],
//     deprecated: false,
//     necessity: "MINIMUM",
//   },
//   {
//     variableName: "zipcode-town-province",
//     localizedVariableName: null,
//     variables: [
//       {
//         variableName: "zipcode",
//         dataType: "number",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "town",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "province",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//     ],
//     deprecated: false,
//     necessity: "MINIMUM",
//   },
//   {
//     variableName: "address",
//     localizedVariableName: null,
//     variables: [
//       {
//         variableName: "fullAddress",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "addressType",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "addressName",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "addressNumber",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "addressTypeName",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "addressTypeNameNumber",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "addressSupplement",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "floor",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "door",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "block",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "stair",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//     ],
//     deprecated: false,
//     necessity: "STANDARD_MINIMUM",
//   },
//   {
//     variableName: "category-type-brand",
//     localizedVariableName: null,
//     variables: [
//       {
//         variableName: "category",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "type",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "brand",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//     ],
//     deprecated: false,
//     necessity: "PERFECT",
//   },
//   {
//     variableName: "subcategory-model",
//     localizedVariableName: null,
//     variables: [
//       {
//         variableName: "subcategory",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//       {
//         variableName: "model",
//         dataType: "string",
//         localizedVariableName: null,
//         deprecated: false,
//         necessity: null,
//       },
//     ],
//     deprecated: false,
//     necessity: "PERFECT",
//   },
// ];
export const initialVariablesData = {
  businessCaseId: "5fe1dec0b7a84c41e12b1221",
  businessCaseName: "Portfolio",
  localizedName: null,
  variables: [
    {
      variableName: "documentNumber",
      dataType: "string",
      localizedVariableName: null,
      deprecated: false,
      necessity: "MINIMUM",
    },
    {
      variableName: "birthday",
      dataType: "date",
      localizedVariableName: null,
      deprecated: false,
      necessity: "MINIMUM",
    },
    {
      variableName: "target",
      dataType: "number",
      localizedVariableName: null,
      deprecated: false,
      necessity: "STANDARD_MINIMUM",
    },
    {
      variableName: "email",
      dataType: "string",
      localizedVariableName: null,
      deprecated: false,
      necessity: "STANDARD_MINIMUM",
    },
    {
      variableName: "phone",
      dataType: "string",
      localizedVariableName: null,
      deprecated: false,
      necessity: "STANDARD_MINIMUM",
    },
    {
      variableName: "amount",
      dataType: "number",
      localizedVariableName: null,
      deprecated: false,
      necessity: "STANDARD_MINIMUM",
    },
    {
      variableName: "share",
      dataType: "number",
      localizedVariableName: null,
      deprecated: false,
      necessity: "STANDARD_MINIMUM",
    },
    {
      variableName: "timeFrame",
      dataType: "number",
      localizedVariableName: null,
      deprecated: false,
      necessity: "STANDARD_MINIMUM",
    },
    {
      variableName: "productType",
      dataType: "string",
      localizedVariableName: null,
      deprecated: false,
      necessity: "STANDARD_MINIMUM",
    },
    {
      variableName: "channel",
      dataType: "string",
      localizedVariableName: null,
      deprecated: false,
      necessity: "STANDARD_MINIMUM",
    },
    {
      variableName: "modality",
      dataType: "string",
      localizedVariableName: null,
      deprecated: false,
      necessity: "STANDARD_MINIMUM",
    },
    {
      variableName: "risk",
      dataType: "number",
      localizedVariableName: null,
      deprecated: false,
      necessity: "PERFECT",
    },
    {
      variableName: "operationDate",
      dataType: "date",
      localizedVariableName: null,
      deprecated: false,
      necessity: "PERFECT",
    },
    {
      variableName: "registrationType",
      dataType: "string",
      localizedVariableName: null,
      deprecated: false,
      necessity: "PERFECT",
    },
    {
      variableName: "paymentMethod",
      dataType: "string",
      localizedVariableName: null,
      deprecated: false,
      necessity: "PERFECT",
    },
  ],
  groupVariables: [
    {
      variableName: "name",
      localizedVariableName: null,
      variables: [
        {
          variableName: "fullName",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
        {
          variableName: "name",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
        {
          variableName: "surname1",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
        {
          variableName: "surname2",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
        {
          variableName: "lastName",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
      ],
      deprecated: false,
      necessity: "MINIMUM",
      validCombinations: [
        ["fullName"],
        ["name", "surname1", "surname2"],
        ["name", "lastName"],
      ],
      minimumVariables: [
        ["fullname"],
        ["name", "surname1"],
        ["name", "lastname"],
      ],
    },
    {
      variableName: "zipCodeTownProvince",
      localizedVariableName: null,
      variables: [
        {
          variableName: "zipCode",
          dataType: "number",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
        {
          variableName: "town",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
        {
          variableName: "province",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
      ],
      deprecated: false,
      necessity: "MINIMUM",
      validCombinations: [["zipCode", "town", "province"]],
      minimumVariables: [["zipCode"], ["town", "province"]],
    },
    {
      variableName: "address",
      localizedVariableName: null,
      variables: [
        {
          variableName: "fullAddress",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
        {
          variableName: "addressType",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
        {
          variableName: "addressName",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
        {
          variableName: "addressNumber",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
        {
          variableName: "addressTypeName",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
        {
          variableName: "addressTypeNameNumber",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
        {
          variableName: "addressSupplement",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
        {
          variableName: "floor",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
        {
          variableName: "door",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
        {
          variableName: "block",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
        {
          variableName: "stair",
          dataType: "string",
          localizedVariableName: null,
          deprecated: false,
          necessity: null,
        },
      ],
      deprecated: false,
      necessity: "STANDARD_MINIMUM",
      validCombinations: [
        ["fullAddress"],
        [
          "addressType",
          "addressName",
          "addressNumber",
          "floor",
          "door",
          "block",
          "stair",
          "addressSupplement",
        ],
        [
          "addressTypeName",
          "addressNumber",
          "floor",
          "door",
          "block",
          "stair",
          "addressSupplement",
        ],
        [
          "addressTypeNameNumber",
          "floor",
          "door",
          "block",
          "stair",
          "addressSupplement",
        ],
      ],
      minimumVariables: [
        ["fullAddress"],
        ["addressType", "addressName", "addressNumber"],
        ["addressTypeName", "addressNumber"],
        ["addressTypeNameNumber"],
      ],
    },
  ],
  vertexes: null,
  parentBusinessCase: "5fe1ccb9a30370626a8a89f0",
  childrenBusinessCases: [],
  createdBy: "user-unknown",
  createdDate: "2020-12-21T11:20:30.796",
  lastModifiedBy: null,
  lastModifiedDate: null,
  deletedBy: null,
  deletedDate: null,
  versionNumber: 0,
};
export const initialFileColumnsData = {
  businessCaseid: "5fdddd672ade942066733d95",
  name: "QA test dataset",
  clientId: "5f8fd9d9d401e2d724266535",
  projectId: "5f8fda32d401e2d724266536",
  fileName: "dataset.csv",
  filePath:
    "/client/5f8fd9d9d401e2d724266535/project/5f8fda32d401e2d724266536/dataset/dataset name",
  originalSize: "4479",
  status: "PRE_MAPPING",
  totalRowsNumber: "19",
  hocelotMappings: [],
  clientMappings: [],
  targetMappings: [],
  fileColumns: [
    {
      originalColumnName: "documentNumberCustomer",
      dataTypes: ["string"],
      numberColumn: "1",
      possibleMappings: [""],
      sampleValues: [
        "01234567U",
        "76543215V",
        "23455544V",
        "99999999N",
        "11111111X",
      ],
    },
    {
      originalColumnName: "monthly_payment",
      dataTypes: ["double", "string"],
      numberColumn: "17",
      possibleMappings: [],
      sampleValues: ["91.58", "91.85", "125.6", "53.27", "132.79"],
    },
    {
      originalColumnName: "fechaContratacion",
      dataTypes: ["date", "string"],
      numberColumn: "12",
      possibleMappings: ["birthday"],
      sampleValues: [
        "01-03-2018",
        "01-03-2018",
        "01-03-2018",
        "01-03-2018",
        "01-03-2018",
      ],
    },
    {
      originalColumnName: "phone",
      dataTypes: ["integer", "string"],
      numberColumn: "8",
      possibleMappings: ["phoneNumber"],
      sampleValues: [
        "670748586",
        "636742903",
        "675747176",
        "687787190",
        "649430638",
      ],
    },
    {
      originalColumnName: "fechaNacimiento",
      dataTypes: ["date", "string"],
      numberColumn: "11",
      possibleMappings: ["birthday"],
      sampleValues: [
        "12-12-1992",
        "04-04-1974",
        "10-10-1990",
        "04-04-1984",
        "05-05-1985",
      ],
    },
    {
      originalColumnName: "documentNumber",
      dataTypes: ["string"],
      numberColumn: "2",
      possibleMappings: ["documentNumber"],
      sampleValues: [
        "00647449E",
        "00697861H",
        "00640208A",
        "00377193Q",
        "00377402H",
      ],
    },
    {
      originalColumnName: "n_monthly_payments",
      dataTypes: ["double", "string"],
      numberColumn: "16",
      possibleMappings: [],
      sampleValues: ["12.0", "12.0", "10.0", "30.0", "10.0"],
    },
    {
      originalColumnName: "fullName",
      dataTypes: ["string"],
      numberColumn: "0",
      possibleMappings: [""],
      sampleValues: [
        "amparo lajas dominguez",
        "adolfo gayo",
        "pedro victorio salcedo lopez",
        "cayetano martin nombela",
        "claudio carlos lopez diego",
      ],
    },
    {
      originalColumnName: "nameCustomer",
      dataTypes: ["string"],
      numberColumn: "18",
      possibleMappings: [""],
      sampleValues: [
        "amparo lajas dominguez",
        "adolfo gayo",
        "pedro victorio salcedo lopez",
        "cayetano martin nombela",
        "claudio carlos lopez diego",
      ],
    },
    {
      originalColumnName: "apellidosCLI",
      dataTypes: ["string"],
      numberColumn: "19",
      possibleMappings: [""],
      sampleValues: [
        "lajas dominguez",
        "gayo",
        "salcedo lopez",
        "martin nombela",
        "lopez diego",
      ],
    },
    {
      originalColumnName: "fullAddress",
      dataTypes: ["string"],
      numberColumn: "3",
      possibleMappings: [],
      sampleValues: [
        "AV CONSTITUCION 42 ,10868",
        "AV VALDELAPARRA 120 PL:BAJO PT:E ,28100 ,ALCOBENDAS ,MADRID",
        "AV SALAMANCA 26 BL:10 PL:6 PT:12 ,03130 ,SANTA POLA ,ALICANTE/ALACANT",
        "CL GONZALO CORDOBA 61 PL:3 ,28830 ,SAN FERNANDO DE HENARES ,MADRID",
        "CL SIMONE DE BEAUVOIR 1 BL:5 PL:3 PT:B ,28523 ,RIVAS-VACIAMADRID ,MADRID",
      ],
    },
    {
      originalColumnName: "credit_amount",
      dataTypes: ["double", "string"],
      numberColumn: "14",
      possibleMappings: [],
      sampleValues: ["1099.0", "1102.15", "1256.0", "1597.99", "1327.9"],
    },
    {
      originalColumnName: "address",
      dataTypes: ["string"],
      numberColumn: "7",
      possibleMappings: [],
      sampleValues: [
        "AV CONSTITUCION 42",
        "AV VALDELAPARRA 120 BAJO E",
        "AV SALAMANCA 26 Bloque 10 6Pta 12",
        "CL GONZALO CORDOBA 61 3",
        "CL SIMONE DE BEAUVOIR 1 Bloque 5 3B",
      ],
    },
    {
      originalColumnName: "fechaFinalizacion",
      dataTypes: ["date", "string"],
      numberColumn: "13",
      possibleMappings: ["birthday"],
      sampleValues: [
        "15-12-2020",
        "15-12-2020",
        "15-12-2020",
        "15-12-2020",
        "15-12-2020",
      ],
    },
    {
      originalColumnName: "province",
      dataTypes: ["string"],
      numberColumn: "4",
      possibleMappings: ["zipCodeTownProvince"],
      sampleValues: ["CACERES", "MADRID", "ALICANTE", "MADRID", "MADRID"],
    },
    {
      originalColumnName: "phone2",
      dataTypes: ["integer", "string"],
      numberColumn: "9",
      possibleMappings: [],
      sampleValues: [
        "34653399395",
        "34916741587",
        "34649430622",
        "34649430622",
      ],
    },
    {
      originalColumnName: "tin",
      dataTypes: ["double", "string"],
      numberColumn: "15",
      possibleMappings: [],
      sampleValues: ["12.0", "13.0", "14.0", "15.0", "16.0"],
    },
    {
      originalColumnName: "email",
      dataTypes: ["string"],
      numberColumn: "10",
      possibleMappings: ["email"],
      sampleValues: [
        "pilar.mafer@yahoo.es",
        "ami.madrid@hotmail.es",
        "vicentegperales@hotmail.com",
        "ami.madrid@hotmail.es",
        "vicentegperales@hotmail.com",
      ],
    },
    {
      originalColumnName: "town",
      dataTypes: ["string"],
      numberColumn: "5",
      possibleMappings: ["zipCodeTownProvince"],
      sampleValues: [
        "HERNAN",
        "ALCOBENDAS",
        "SANTA POLA",
        "SAN FERNANDO DE HENARES",
        "RIVAS-VACIAMADRID",
      ],
    },
    {
      originalColumnName: "zipCode",
      dataTypes: ["integer", "string"],
      numberColumn: "6",
      possibleMappings: ["zipCodeTownProvince"],
      sampleValues: ["10868", "28100", "03130", "28830", "28523"],
    },
  ],
  createdBy: "user-unknown",
  createdDate: "2020-12-19T11:00:55.518Z",
  lastModifiedBy: "user-unknown",
  lastModifiedDate: "2020-12-19T11:00:56.707Z",
  versionNumber: 2,
  _class: "com.hocelot.platform.daas.dataset.entities.DatasetEntity",
};
